encoding: utf-8
baseurl: /BIO181G
url: SchwartzLabURI.github.io/BIO181G/
permalink: /:title/
disqus_shortname: BIO181G
prose:
  media: /img
  ignore:
    - /_includes
    - /_layouts
    - /_sass
    - /fonts
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "course_page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "category"
        field:
          element: "hidden"
          value: "content"
